FROM python:3
ENV PYTHONUNBUFFERED 1

# create root directory for our project in the container
RUN mkdir /confiscated_ms

# Set the working directory to /music_service
WORKDIR /confiscated_ms

# Copy the current directory contents into the container at /music_service
ADD . /confiscated_ms/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

