version: "2.1"

services:
    confiscated-ms:
        build: confiscated_ms/.
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        container_name: confiscated_ms
        ports:
            - "8000:8000"
        depends_on:
            - confiscated-db
            
    confiscated-db:
        image: mysql:5.7
        ports:
        - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: citepp
            MYSQL_DATABASE: confiscated_ms
            MYSQL_USER: cite
            MYSQL_PASSWORD: citepp
