version: "2"

services:   
            
    confiscated-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: citepp
            MYSQL_DATABASE: confiscated_db
            MYSQL_USER: cite
            MYSQL_PASSWORD: citepp
            MYSQL_HOST: confiscated-db
            MYSQL_HOST: 3306
            MYSQL_DATA: /var/lib/mysql
        ports:
            - '3307:3306'
        restart: always
        volumes:
            - my-datavolume:/var/lib/mysql
            
    confiscated-ms:
        build: confiscated_ms/.
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:4003"
        ports:
            - "4003:4003"
        depends_on:
            - confiscated-db
        restart: on-failure
            
volumes:
    my-datavolume:
