# Generated by Django 2.2.2 on 2019-07-18 15:02

import confiscatedapi.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=255)),
                ('recoverable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('delivery_point', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('confiscation_date', models.DateField(validators=[confiscatedapi.models.validate_date])),
                ('units', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('passenger', models.CharField(max_length=24)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confiscatedapi.Category')),
            ],
            options={
                'ordering': ('confiscation_date',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='confiscatedapi.Delivery'),
        ),
    ]
