# Generated by Django 2.2.1 on 2019-06-04 21:00

import confiscatedapi.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('recoverable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('delivery_point', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('confiscation_date', models.DateField(validators=[confiscatedapi.models.validate_date])),
                ('units', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('passenger', models.CharField(max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confiscatedapi.Category')),
            ],
            options={
                'ordering': ('confiscation_date',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='confiscatedapi.Delivery'),
        ),
    ]
