# Generated by Django 2.2.1 on 2019-05-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('recoverable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('delivery_point', models.CharField(choices=[('P01', 'Punto 01'), ('P02', 'Punto 02'), ('P03', 'Punto 03'), ('P04', 'Punto 04'), ('P05', 'Punto 05')], default='P01', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('confiscation_date', models.DateField(null=True)),
                ('confiscation_time', models.TimeField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('passenger', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confiscatedapi.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='confiscatedapi.Delivery'),
        ),
    ]
