# Generated by Django 2.2.1 on 2019-06-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confiscatedapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
