# Generated by Django 2.2.1 on 2019-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confiscatedapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_point',
            field=models.CharField(choices=[('NNN', 'None'), ('PN1', 'Norte'), ('PC1', 'Centro'), ('PS1', 'Sur'), ('PC8', 'Cabina 08')], default='NNN', max_length=3),
        ),
    ]
