# Generated by Django 2.2.1 on 2019-05-21 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confiscatedapi', '0002_auto_20190518_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='confiscation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quiantity',
        ),
        migrations.AddField(
            model_name='item',
            name='confiscation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='confiscation_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
